version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.9.4
     steps:
       - checkout
       - run: npm i
       - run: npm run build 
       - run: firebase deploy --token=$FIREBASE_TOKEN --non-interactive